// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messaging/channels/user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShowcaseRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowcaseRequest) Reset()         { *m = ShowcaseRequest{} }
func (m *ShowcaseRequest) String() string { return proto.CompactTextString(m) }
func (*ShowcaseRequest) ProtoMessage()    {}
func (*ShowcaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{0}
}
func (m *ShowcaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowcaseRequest.Unmarshal(m, b)
}
func (m *ShowcaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowcaseRequest.Marshal(b, m, deterministic)
}
func (dst *ShowcaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowcaseRequest.Merge(dst, src)
}
func (m *ShowcaseRequest) XXX_Size() int {
	return xxx_messageInfo_ShowcaseRequest.Size(m)
}
func (m *ShowcaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowcaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowcaseRequest proto.InternalMessageInfo

func (m *ShowcaseRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ShowcaseResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowcaseResponse) Reset()         { *m = ShowcaseResponse{} }
func (m *ShowcaseResponse) String() string { return proto.CompactTextString(m) }
func (*ShowcaseResponse) ProtoMessage()    {}
func (*ShowcaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{1}
}
func (m *ShowcaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowcaseResponse.Unmarshal(m, b)
}
func (m *ShowcaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowcaseResponse.Marshal(b, m, deterministic)
}
func (dst *ShowcaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowcaseResponse.Merge(dst, src)
}
func (m *ShowcaseResponse) XXX_Size() int {
	return xxx_messageInfo_ShowcaseResponse.Size(m)
}
func (m *ShowcaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowcaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowcaseResponse proto.InternalMessageInfo

func (m *ShowcaseResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type CreateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{2}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateResponse struct {
	Response             bool     `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{3}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{4}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateResponse struct {
	Response             bool     `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{5}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type UpdateLocationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLocationRequest) Reset()         { *m = UpdateLocationRequest{} }
func (m *UpdateLocationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationRequest) ProtoMessage()    {}
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{6}
}
func (m *UpdateLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationRequest.Unmarshal(m, b)
}
func (m *UpdateLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationRequest.Merge(dst, src)
}
func (m *UpdateLocationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationRequest.Size(m)
}
func (m *UpdateLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationRequest proto.InternalMessageInfo

func (m *UpdateLocationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateLocationResponse struct {
	Response             bool     `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLocationResponse) Reset()         { *m = UpdateLocationResponse{} }
func (m *UpdateLocationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationResponse) ProtoMessage()    {}
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{7}
}
func (m *UpdateLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationResponse.Unmarshal(m, b)
}
func (m *UpdateLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationResponse.Merge(dst, src)
}
func (m *UpdateLocationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationResponse.Size(m)
}
func (m *UpdateLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationResponse proto.InternalMessageInfo

func (m *UpdateLocationResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type RegisterTargetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTargetRequest) Reset()         { *m = RegisterTargetRequest{} }
func (m *RegisterTargetRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterTargetRequest) ProtoMessage()    {}
func (*RegisterTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{8}
}
func (m *RegisterTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTargetRequest.Unmarshal(m, b)
}
func (m *RegisterTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTargetRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTargetRequest.Merge(dst, src)
}
func (m *RegisterTargetRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterTargetRequest.Size(m)
}
func (m *RegisterTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTargetRequest proto.InternalMessageInfo

func (m *RegisterTargetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterTargetRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type RegisterTargetResponse struct {
	Response             bool     `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTargetResponse) Reset()         { *m = RegisterTargetResponse{} }
func (m *RegisterTargetResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterTargetResponse) ProtoMessage()    {}
func (*RegisterTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_696fba13f42459b1, []int{9}
}
func (m *RegisterTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTargetResponse.Unmarshal(m, b)
}
func (m *RegisterTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTargetResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTargetResponse.Merge(dst, src)
}
func (m *RegisterTargetResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterTargetResponse.Size(m)
}
func (m *RegisterTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTargetResponse proto.InternalMessageInfo

func (m *RegisterTargetResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

func init() {
	proto.RegisterType((*ShowcaseRequest)(nil), "user.ShowcaseRequest")
	proto.RegisterType((*ShowcaseResponse)(nil), "user.ShowcaseResponse")
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "user.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "user.UpdateResponse")
	proto.RegisterType((*UpdateLocationRequest)(nil), "user.UpdateLocationRequest")
	proto.RegisterType((*UpdateLocationResponse)(nil), "user.UpdateLocationResponse")
	proto.RegisterType((*RegisterTargetRequest)(nil), "user.RegisterTargetRequest")
	proto.RegisterType((*RegisterTargetResponse)(nil), "user.RegisterTargetResponse")
}

func init() {
	proto.RegisterFile("messaging/channels/user/user.proto", fileDescriptor_user_696fba13f42459b1)
}

var fileDescriptor_user_696fba13f42459b1 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbf, 0x4b, 0xc6, 0x30,
	0x10, 0x86, 0xf9, 0x8a, 0x94, 0x7a, 0x60, 0x95, 0x42, 0x4b, 0x71, 0x51, 0xb2, 0xa8, 0x20, 0xed,
	0xa0, 0xbb, 0xa0, 0x93, 0xe0, 0x54, 0x75, 0x71, 0x8b, 0xed, 0x91, 0x06, 0x34, 0xa9, 0xb9, 0x14,
	0xff, 0x7d, 0x49, 0xfa, 0x43, 0x2c, 0xd4, 0xaf, 0x4b, 0xb8, 0x97, 0x3c, 0x3c, 0x07, 0xf7, 0x02,
	0xfb, 0x44, 0x22, 0x2e, 0xa4, 0x12, 0x65, 0xdd, 0x72, 0xa5, 0xf0, 0x83, 0xca, 0x9e, 0xd0, 0xf8,
	0xa7, 0xe8, 0x8c, 0xb6, 0x3a, 0x39, 0x70, 0x33, 0xbb, 0x82, 0xe3, 0xe7, 0x56, 0x7f, 0xd7, 0x9c,
	0xb0, 0xc2, 0xaf, 0x1e, 0xc9, 0x26, 0x19, 0x84, 0xee, 0xeb, 0xb1, 0xc9, 0x77, 0xe7, 0xbb, 0xcb,
	0xc3, 0x6a, 0x4c, 0xac, 0x80, 0x93, 0x5f, 0x94, 0x3a, 0xad, 0x08, 0x93, 0x53, 0x88, 0xcc, 0x38,
	0x8f, 0xf4, 0x9c, 0xd9, 0x19, 0x1c, 0x3d, 0x18, 0xe4, 0x76, 0x16, 0xc7, 0x10, 0xc8, 0x49, 0x1a,
	0xc8, 0x86, 0x5d, 0x43, 0x3c, 0x01, 0x2b, 0xba, 0xe8, 0xaf, 0xee, 0xb5, 0x6b, 0xfe, 0xd7, 0x4d,
	0xc0, 0x06, 0xdd, 0x05, 0xa4, 0x03, 0xfd, 0xa4, 0x6b, 0x6e, 0xa5, 0x56, 0x6b, 0xda, 0x5b, 0xc8,
	0x96, 0xe0, 0x06, 0xfd, 0x1d, 0xa4, 0x15, 0x0a, 0x49, 0x16, 0xcd, 0x0b, 0x37, 0x02, 0xed, 0x8a,
	0xde, 0x5d, 0xdb, 0x7a, 0x20, 0x0f, 0x86, 0x6b, 0x0f, 0xc9, 0xad, 0x5d, 0x0a, 0xf6, 0xaf, 0xbd,
	0x0f, 0xdf, 0x7c, 0xad, 0xef, 0xa1, 0xef, 0xf8, 0xe6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x15,
	0xb5, 0xe1, 0x09, 0x02, 0x00, 0x00,
}
